language: python
arch:
    - amd64
    - arm64
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.7
jobs:
    - arch: arm64
      before_script: "./travis/before-script.sh"
      script:
            apt-get install wkhtmltopdf
            nosetests -w tests      
before_script: "./travis/before-script.sh"
script: nosetests -w tests
notifications:
  email: false
